name: GithubPages

on:
  push:
    branches:
      - source  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Grant Write Permissions
        run: |
          cd /var/lib
          sudo chmod -R a+w gems/      
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
          npm install
      - name: Build
        run: |
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AUTO_DEPLOY }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
